# Aliases

alias yt="yarn test"
alias yj="yarn jest --watch"
alias yju="yarn jest --u"
alias ytt="yarn test:types"
alias yl="yarn test:lint"
alias rn="react-native"
alias rna="yarn android"
alias rnise="react-native run-ios --scheme MateraDev --configuration DebugDev --simulator=\"iPhone SE (2nd generation)\""
alias rni='yarn ios'
alias ad="adb devices -l"
alias emu23="emulator -avd Nexus_5X_API_23 &"
alias emu="emulator -avd Nexus_6_API_26_1 &"
alias nvimrc="nvim ~/.config/nvim/init.vim"
alias nvimzshrc="nvim ~/.zshrc"
alias g="git"
alias gcz="git cz --no-verify"
alias gst="git status"
alias ll="ls -larth"
alias android="open -a /Applications/Android\ Studio.app"
alias ...="cd ../.."
alias ....="cd ../../.."
